export const ChipItems = [
  'Tudo',
  'Jogos',
  'Podcast',
  'Desenvolvimento de software',
  'Porgramação de computadores',
  'Navio',
  'Mussica',
  'Inovação',
  'Fisica',
  'Fabrica',
  'Cabine',
  'Mixes',
  'Ao vivo',
  'Historia',
  'Arte',
  'Televisão',
  'Viagem',
  'Smartphone',
  'Iphone',
  'Latam'
]